MODEL:
  TYPE: swin
  NAME: swin_tiny_ft
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 120
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 150
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-4
  WARMUP_LR: 2e-4
  MIN_LR: 2e-4
