MODEL:
  TYPE: TAViT
  NAME: TAViT_ft
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 120
  FT: True
  TAViT:
    PATCH_SIZE: 4
    EMBED_DIM: [96, 192, 384]
    DEPTHS: [3, 3, 27]
    NUM_HEADS: [3, 6, 12]
    MLP_RATIO: 2.
    LAYER_DIM: [48, 48, 48]
TRAIN:
  EPOCHS: 150
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-4
  WARMUP_LR: 2e-4
  MIN_LR: 2e-4